name: Deploy Node.js Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Deploy to VPS
      env:
        VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
        VPS_USER: ${{ secrets.VPS_USER }}
        VPS_IP: ${{ secrets.VPS_IP }}
        DATABASE_ACCESS: ${{DATABASE_ACCESS}}
        ACCESS_TOKEN_SECRET: ${{ACCESS_TOKEN_SECRET}}
        PORT: ${{BACK_PORT}}
        CLIENT: ${{CLIENT}}
        STRIPE_PRIVATE_KEY: ${{STRIPE_PRIVATE_KEY}}
      run: |
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
        ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP "
          cd /var/www/unow-back &&
          git pull &&
          npm install &&
          pm2 restart all || pm2 start server.js --name unow-back
        "
