name: Deploy Node.js Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Deploy to VPS
      env:
        VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
        VPS_USER: ${{ secrets.VPS_USER }}
        VPS_IP: ${{ secrets.VPS_IP }}
        DATABASE_ACCESS: ${{ secrets.DATABASE_ACCESS }}
        ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        PORT: ${{ secrets.BACK_PORT }}
        CLIENT: ${{ secrets.CLIENT }}
        STRIPE_PRIVATE_KEY: ${{ secrets.STRIPE_PRIVATE_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sshpass -p $VPS_PASSWORD ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP "
          if [ ! -d /var/www/unow-back/.git ]; then
            rm -rf /var/www/unow-back
            git clone https://$GIT_TOKEN@github.com/TomIA24/unow-back.git /var/www/unow-back
          else
            cd /var/www/unow-back &&
            git pull
          fi
          cd /var/www/unow-back &&
          npm install &&
          pm2 restart all || pm2 start server.js --name unow-back
        "
